/* Generated By:JJTree&JavaCC: Do not edit this line. PatientModelQueryLanguageConstants.java */
package edu.illinois.mdpnp.patient.pmql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatientModelQueryLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE = 1;
  /** RegularExpression Id. */
  int SPACE = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int START_TOKEN = 5;
  /** RegularExpression Id. */
  int FUNCTION = 6;
  /** RegularExpression Id. */
  int WORD = 7;
  /** RegularExpression Id. */
  int OVER = 8;
  /** RegularExpression Id. */
  int TIME_UNIT = 9;
  /** RegularExpression Id. */
  int TIME = 10;
  /** RegularExpression Id. */
  int FROM_IDENTIFIER = 11;
  /** RegularExpression Id. */
  int FROM = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NEWLINE>",
    "<SPACE>",
    "<LETTER>",
    "<DIGIT>",
    "<START_TOKEN>",
    "<FUNCTION>",
    "<WORD>",
    "<OVER>",
    "<TIME_UNIT>",
    "<TIME>",
    "<FROM_IDENTIFIER>",
    "<FROM>",
  };

}
