/* Generated By:JavaCC: Do not edit this line. PatientModelQueryLanguageTreeConstants.java Version 5.0 */
package edu.illinois.mdpnp.patient.pmql;

public interface PatientModelQueryLanguageTreeConstants
{
  public int JJTSTART = 0;


  public String[] jjtNodeName = {
    "Start",
  };
}
/* JavaCC - OriginalChecksum=6e814785f715a9e5bf5e92cad0c13245 (do not edit this line) */
